apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vm-static
  namespace: vm-consumers
spec:
  destination:
    create: true
    name: vm-static
    overwrite: true
    transformation: {}
  hmacSecretData: true
  mount: secret
  path: vm/static
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: vm-vault
