apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vm-jwt
  namespace: vm-consumers
spec:
  address: https://vault-vm-apps.jose-merchan.sbx.hashidemos.io
  skipTLSVerify: false
