apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vm-aws-jwt
  namespace: vm-consumers
spec:
  destination:
    create: true
    name: vm-aws-jwt
    overwrite: true
    transformation: {}
  mount: aws-vm
  path: sts/demo
  renewalPercent: 50
  vaultAuthRef: vm-jwt
