apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vm-dynamic
  namespace: vm-consumers
spec:
  destination:
    create: true
    name: vm-dynamic
    overwrite: true
    transformation: {}
  mount: database
  path: creds/readonly
  renewalPercent: 50
  vaultAuthRef: vm-vault
