apiVersion: v1
kind: Pod
metadata:
  name: vm-secret-reader
  namespace: vm-consumers
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 86400
    image: busybox:1.37.0
    imagePullPolicy: IfNotPresent
    name: reader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /csi
      name: csi
      readOnly: true
    - mountPath: /static
      name: static
      readOnly: true
    - mountPath: /dynamic
      name: dynamic
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: consumer
  serviceAccountName: consumer
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: vm-vault
    name: csi
  - name: static
    secret:
      defaultMode: 420
      secretName: vm-static
  - name: dynamic
    secret:
      defaultMode: 420
      secretName: vm-dynamic
