apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vm-vault
  namespace: vm-consumers
spec:
  parameters:
    audience: vault
    objects: |
      - objectName: static
        secretKey: value
        secretPath: secret/data/vm/static
      - objectName: db-user
        secretKey: username
        secretPath: database/creds/readonly
      - objectName: db-password
        secretKey: password
        secretPath: database/creds/readonly
    roleName: consumer
    vaultAddress: https://vault-vm-apps.jose-merchan.sbx.hashidemos.io
    vaultAuthMountPath: vm-kubernetes
  provider: vault
