apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: engine
  namespace: vm-consumers
rules:
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - consumer
  resources:
  - roles
  verbs:
  - get
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - update
  - delete
