apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consumer
  namespace: vm-consumers
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - vaultconnections
  - vaultauths
  - vaultstaticsecrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
