apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vm-gha-delivery
  namespace: vm-consumers
spec:
  destination:
    create: true
    name: vm-gha-delivery
    overwrite: false
    transformation: {}
  hmacSecretData: true
  mount: secret
  namespace: vm-gha
  path: application/ui
  refreshAfter: 10s
  rolloutRestartTargets:
  - kind: Deployment
    name: vm-gha-app
  type: kv-v2
  vaultAuthRef: vm-vault
