apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data
  namespace: vm-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
  volumeMode: Filesystem
