apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMTCCAhmgAwIBAgIQS1LZgomVfWtDfdAHxajcezANBgkqhkiG9w0BAQsFADAn
    MRAwDgYDVQQKEwdBV1MgRUtTMRMwEQYDVQQDEwprdWJlcm5ldGVzMB4XDTI2MDky
    MzA5MjkwMVoXDTMxMDkyMjA5MjkwMVowJzEQMA4GA1UEChMHQVdTIEVLUzETMBEG
    A1UEAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    ALW1w+54ordLHFLWWb9aoyJWp/9jPp5fnkx1+I1kX7cYdUzrs1ZC7Xu7VhWObyPa
    0h2MqKZEgSZalxyM4wLqYKqLbJcxwp2CO4ka602yg2ZsjmGSCRbLX5dowfLlfCw5
    xknJMOsy2ze8IJmjA/rPrfLb/HtXjXKmjR8Z8304mZQV7H86mk9grV0LMsEWKmAZ
    d1dXfjl3GAJxMry3+8RmC1DxFz5XvE9hdK7RvLTpGSBSjCIgDykd+1H1kDqtZZaF
    PkZPcI6wo++NpqVdd4960f5wiZK9iyWtIBsr5cTHVtAmGF3EzF1tO3/StQjO7IXF
    q3UcduwvrN4188hIkIb0uz0CAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1Ud
    EwEB/wQFMAMBAf8wHQYDVR0OBBYEFGhsLGJmOw6Z/8rFBwWqsEYRrsBSMBUGA1Ud
    EQQOMAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAEpDYOMWNqJOaCnJ
    xP8gVBkhvh1FXlSr71GAwQOUo5o8cHO7pCk0zroNJxzF57HUWGcr+LOzQmK/dh4J
    eVFUUWfVEoVMcUXI9955EeLehNG6OBwl7DQhueEWL26nxUaaiCEWawaaM3X3gLqQ
    LDo0ooswHd3j5Q9I5oAqXVsLOBh241JADzFOEqxTA39v4Yc0DowJYGF7hEhoYw+V
    iyL2mXex09XvB6eBXw4ZdRQ9pjlXAyMTHxp/hu5dCfgRiUfFoqZ8n54ovHKZ6OlV
    0pkTYHqOP2UbE61e5cZgzKPXV2/JErHx58mHAEw8t5W/5qyB58eBgmfBw0o7Ne6T
    ZvN7q8c=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: kube-root-ca.crt
  namespace: vm-monitoring
