apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
    - bearer_token_file: /credentials/token
      job_name: vault-vm
      metrics_path: /v1/sys/metrics
      params:
        format:
        - prometheus
      scheme: https
      static_configs:
      - targets:
        - 10.1.159.67:8200
        - 10.1.172.196:8200
        - 10.1.129.167:8200
        - 10.1.159.105:8200
        - 10.1.167.46:8200
        - 10.1.134.57:8200
      tls_config:
        ca_file: /credentials/ca.pem
kind: ConfigMap
metadata:
  name: prometheus
  namespace: vm-monitoring
